import Footer from "@/components/Footer";
import Nav from "@/components/nav";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`bg-[#041F31] text-[#BDEBEA] ${montserrat.className}`}>
        <div className="max-w-6xl mx-auto">
          <Nav />
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
